# Copyright 2025 Marcelo Parisi (github.com/feitnomore)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: publish-docs
  namespace: kvm-cicd
spec:
  description: Published mkdocs documentation website
  params:
    - name: IMAGE_REGISTRY
      description: The registry URL.
      type: string
    - name: CLI_IMAGE_NAME
      description: The CLI Image Name.
      type: string
    - name: CLI_IMAGE_TAG
      description: The CLI Image Tag.
      type: string
    - name: SUBDIRECTORY
      description: "Subdirectory within the source workspace where the Makefile is located."
      type: string
      default: "kubevirt-manager-docs"
    - name: pipelinerun-name
      description: "The name of the current PipelineRun to inspect."
      type: string

  workspaces:
    - name: source
      description: "A workspace containing the source code to be built."
    - name: artifacts
      description: "A workspace to store build artifacts."
      optional: true
    - name: shared-output
      description: "Workspace for storing logs and output files."

  steps:
    - name: mkdocs-publish
      image: $(params.IMAGE_REGISTRY)/$(params.CLI_IMAGE_NAME):$(params.CLI_IMAGE_TAG)
      imagePullPolicy: Always
      env:
        - name: FTP_USER
          valueFrom:
            secretKeyRef:
              name: ftp-credentials
              key: FTP_USER
        - name: FTP_PASS
          valueFrom:
            secretKeyRef:
              name: ftp-credentials
              key: FTP_PASS
        - name: FTP_HOST
          valueFrom:
            secretKeyRef:
              name: ftp-credentials
              key: FTP_HOST
      workingDir: $(workspaces.source.path)/$(params.SUBDIRECTORY)
      script: |
        #!/bin/bash
        set -e

        export FTP_PATH="/domains/docs.kubevirt-manager.io/public_html"

        echo "--- MKDOCS PUBLISH SCRIPT START ---"

        # Delete artifacts
        lftp -c "set ssl:verify-certificate no; open -u ${FTP_USER},${FTP_PASS} ${FTP_HOST}; rm -r -f ${FTP_PATH}/*"

        # Upload artifacts
        lftp -c "set ssl:verify-certificate no; open -u ${FTP_USER},${FTP_PASS} ${FTP_HOST}; mirror -R ./site/ ${FTP_PATH}/"
        
        echo "--- MKDOCS PUBLISH SCRIPT END ---"
